
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: tooba #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_blog_development

test:
  <<: *default
  database: simple_blog_test

production:
  <<: *default
  database: simple_blog_production
  username: postgres
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
